Hello world pt2

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -7,12 +7,15 @@ jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      -run: echo "Hello, World!"
+      - name: Say Hello
+        run: echo "Hello, World!"
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      -run: | 
-      echo "I am"
-      echo "a multi line"
-      echo "script"
+      - name : Failed step
+        run: | 
+        echo "I will fail"
+        exit 1
+      - name: Say Goodbye
+        run: echo "Goodbye"
     
